#!/usr/bin/python
# -*- coding: utf-8 -*-

__author__ = "Evyatar Orbach"
__email__ = "evyataro@gmail.com"
'''Exercise 17
Create a program that will play the “cows and bulls” game with the user. The game works like this

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''

import random
import string
number = random.sample(string.digits,4)
while(True):
    cows = 0
    bulls = 0
    geuss = raw_input("Please geuss a number\n")
    if(int(geuss) > 999 and int(geuss) < 10000):
        for i in range(4):
            if(geuss[i] == number[i]):
                cows += 1
            elif(geuss[i] in number):
                bulls += 1
        if(cows == 4):
            print("You Won!!\n")
            exit()
        else:
            print("You got %d Cows and %d Bulls\n" %(cows,bulls))
    else:
        print("You choose illegal number\n")

